version: '3.4'

services:
  cryptochat:
    image: cryptochat
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8765 --nothreading --noreload"]
    ports:
      - 8765:8765
      - 5678:5678
